// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Sword":return img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.........5....................
........5d....................
........b5....................
........b5....................
e868888855dbddbdddbdbddbdbddbd
d9868866dddbbdbbbbbbbddddddbd.
5688868665dddddddddddddddddd..
........55....................
........55....................
........b5....................
........db....................
.........d....................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
